In [1]:
#iris logistic


# Logistic Regression with Scikit-learn

from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score,recall_score,f1_score,confusion_matrix

# Step 1: Load the Iris dataset
iris = load_iris()
X = iris.data      # Features
y = iris.target    # Labels (0, 1, 2)

# Step 2: Convert it to a binary classification problem
# Let's classify if the flower is Setosa (0) or not (1)
import numpy as np
y_binary = np.where(y == 0, 1, 0)  # 1 for Setosa, 0 for others

# Step 3: Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y_binary, test_size=0.2, random_state=42)

# Step 4: Create and train the model
model = LogisticRegression()
model.fit(X_train, y_train)

# Step 5: Predict on test data
y_pred = model.predict(X_test)

# Step 6: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Step 7: Print the results
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy      :", accuracy)
print("Precision     :", precision)
print("Recall        :", recall)
print("F1 Score      :", f1)

# Step 8: Predict probabilities
probabilities = model.predict_proba(X_test)
print("\nPredicted Probabilities:\n", probabilities[:5])

Confusion Matrix:
 [[20  0]
 [ 0 10]]
Accuracy      : 1.0
Precision     : 1.0
Recall        : 1.0
F1 Score      : 1.0

Predicted Probabilities:
 [[9.95446142e-01 4.55385779e-03]
 [4.14794882e-02 9.58520512e-01]
 [9.99994600e-01 5.40034424e-06]
 [9.93864864e-01 6.13513643e-03]
 [9.97742514e-01 2.25748581e-03]]


In [2]:
# Logistic Regression on Breast Cancer Dataset

from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Step 1: Load the Breast Cancer dataset
data = load_breast_cancer()
X = data.data        # Features (30 columns)
y = data.target      # Labels: 0 = malignant, 1 = benign

# Step 2: Split the data into training and testing sets
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)  # Feature scaling

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Step 3: Create and train the model
model = LogisticRegression(max_iter=10000)  # increase max_iter for convergence
model.fit(X_train, y_train)

# Step 4: Predict on test data
y_pred = model.predict(X_test)

# Step 5: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Step 6: Print the results
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy      :", accuracy)
print("Precision     :", precision)
print("Recall        :", recall)
print("F1 Score      :", f1)

# Step 7: Predict probabilities
probabilities = model.predict_proba(X_test)
print("\nPredicted Probabilities:\n", probabilities[:5])

Confusion Matrix:
 [[41  2]
 [ 1 70]]
Accuracy      : 0.9736842105263158
Precision     : 0.9722222222222222
Recall        : 0.9859154929577465
F1 Score      : 0.9790209790209791

Predicted Probabilities:
 [[1.14654306e-01 8.85345694e-01]
 [9.99991258e-01 8.74244925e-06]
 [9.96935812e-01 3.06418819e-03]
 [5.01521801e-04 9.99498478e-01]
 [5.98499000e-05 9.99940150e-01]]
